name: Clang-tidy static analyzer check
run-name: ${{github.actor}} is running Code check.

on: [push]

jobs: 
  Clang-tidy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install package
        run: sudo apt-get install -y clang clang-tidy clang-tools clangd python3

      - name: Executing analyzer check
        run: |
              ./clang-tidy-check.sh check_all

