name: Clang-tidy static analyzer check
run-name: ${{github.actor}} is running Code check.

on: [push]

jobs: 
  Clang-tidy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: sudo apt-get install -y clang clang-tidy ninja-build

      - name: Generate compile database
        run: |
          echo "Generating compile database at server ${{runner.os}}"
          cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project
        run: |
            echo "Finish test" 
